name: Cleanup AWS Resources

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: clean up old create instances.
        run: terraform destroy

